name: Update PyPI Stats Monthly

on:
  schedule:
    # Run on the 1st of each month at 02:00 UTC
    - cron: '0 2 1 * *'
  workflow_dispatch: # Allow manual trigger
    inputs:
      username:
        description: 'PyPI username to generate stats for'
        required: true
        default: 'davidsong'

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make
        
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
        
    - name: Generate stats and PNG
      run: |
        USERNAME=${{ github.event.inputs.username || 'davidsong' }} make stats.png
        
    - name: Configure git for cache commits
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Deploy to website
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_PAT }}
      run: |
        make deploy
